# Generated by Django 2.1.5 on 2019-03-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0002_userdetails_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=4)),
                ('age', models.CharField(max_length=3)),
                ('required_date', models.DateField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('hospital_name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('patient_address', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=150)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.UserDetails')),
            ],
            options={
                'db_table': 'RequestDetails',
            },
        ),
    ]
