# Generated by Django 2.1.5 on 2019-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0003_requestdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetails',
            name='blood_unit',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
