# Generated by Django 2.1.5 on 2019-04-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0004_requestdetails_blood_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBloodGroup',
            fields=[
                ('blood_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=4)),
                ('available_units', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BloodBankDetails',
            fields=[
                ('bloodbank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('iso_certified', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'BloodBankDetails',
            },
        ),
        migrations.AddField(
            model_name='availablebloodgroup',
            name='bloodbank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.BloodBankDetails'),
        ),
    ]
