# Generated by Django 2.1.5 on 2019-04-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0005_auto_20190405_2254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availablebloodgroup',
            table='AvailableBloodGroup',
        ),
    ]
